services:
 api:
  build: .
  env_file: ".env"
  ports:
   - "8000:8000"
 db:
  image: postgres:latest
  restart: always
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: Biscuits&Lucy1!
   POSTGRES_DB: remoteok_api
  ports:
   - "5433:5432"
  volumes:
   - postgres_data:/var/lib/postgresql

volumes:
 postgres_data:   